### PR TITLE
Remove artifacts in `build/` dir because it will be generated in user's local environment

### PR DESCRIPTION
**Pull request by kentaro**

### CODE REVIEW

**Comment by amachino** [comment]
When I added `release: npm run build` in Profile, I got an error below:

```
remote: sh: 1: ./node_modules/.bin/tsc: not found
remote: npm ERR! file sh
remote: npm ERR! code ELIFECYCLE
remote: npm ERR! errno ENOENT
remote: npm ERR! syscall spawn
remote: npm ERR! tipether@0.0.1 build: `npm run nearley && ./node_modules/.bin/tsc`
remote: npm ERR! spawn ENOENT
remote: npm ERR! 
remote: npm ERR! Failed at the tipether@0.0.1 build script.
remote: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

It turned out that Heroku will not install `devDependencies` because `NPM_CONFIG_PRODUCTION ` is false.

So, it works if I move `devDependencies` libraries into `dependencies`.
I don't know if this is a good idea, though..

**Comment by kentaro** [comment]
If the deployment process in the production environment requires toolchain, we should include them in `dependencies`, shouldn't we?

**Comment by amachino** [comment]
> If the deployment process in the production environment requires toolchain, we should include them in dependencies

You are right. I will move them to `dependencies`.

**Comment by amachino** [comment]
Ummm.

`npm run build` seems to run when deployed, but got a runtime error.

Its says ` Error: Cannot find module '/app/build/index.js'`

```
remote: -----> Compressing...
remote:        Done: 43.7M
remote: -----> Launching...
remote:  !     Release command declared: this new release will not be available until the command succeeds.
remote:        Released v58
remote:        https://tipether-staging.herokuapp.com/ deployed to Heroku
remote: 
remote: Verifying deploy... done.
remote: Running release command...
remote: 
remote: 
remote: > tipether@0.0.1 build /app
remote: > npm run lint && npm run nearley && tsc
remote: 
remote: 
remote: > tipether@0.0.1 lint /app
remote: > tslint --format stylish --exclude src/command.ts src/**/*.ts
remote: 
remote: 
remote: > tipether@0.0.1 nearley /app
remote: > nearleyc src/command.ne -o src/command.ts
remote: 
remote: Waiting for release.... done.
To https://git.heroku.com/tipether-staging.git
   f4b6b67..395cb4d  master -> master
```

```
2017-12-27T04:07:17.484377+00:00 heroku[worker.1]: State changed from crashed to starting
2017-12-27T04:07:21.613299+00:00 heroku[worker.1]: Starting process with command `node build/index.js`
2017-12-27T04:07:23.948907+00:00 heroku[worker.1]: Process exited with status 1
2017-12-27T04:07:23.883544+00:00 app[worker.1]:     ^
2017-12-27T04:07:23.883508+00:00 app[worker.1]: module.js:538
2017-12-27T04:07:23.883544+00:00 app[worker.1]: 
2017-12-27T04:07:23.883543+00:00 app[worker.1]:     throw err;
2017-12-27T04:07:23.883559+00:00 app[worker.1]:     at Function.Module._resolveFilename (module.js:536:15)
2017-12-27T04:07:23.883552+00:00 app[worker.1]: Error: Cannot find module '/app/build/index.js'
2017-12-27T04:07:23.883560+00:00 app[worker.1]:     at Function.Module._load (module.js:466:25)
2017-12-27T04:07:23.883560+00:00 app[worker.1]:     at Function.Module.runMain (module.js:676:10)
2017-12-27T04:07:23.883561+00:00 app[worker.1]:     at startup (bootstrap_node.js:187:16)
2017-12-27T04:07:23.883561+00:00 app[worker.1]:     at bootstrap_node.js:608:3
2017-12-27T04:07:23.961913+00:00 heroku[worker.1]: State changed from up to crashed
2017-12-27T04:07:23.965196+00:00 heroku[worker.1]: State changed from crashed to starting
2017-12-27T04:07:22.335772+00:00 heroku[worker.1]: State changed from starting to up
2017-12-27T04:07:31.549159+00:00 heroku[worker.1]: Starting process with command `node build/index.js`
2017-12-27T04:07:32.184153+00:00 heroku[worker.1]: State changed from starting to up
2017-12-27T04:07:34.590391+00:00 heroku[worker.1]: State changed from up to crashed
2017-12-27T04:07:34.575529+00:00 heroku[worker.1]: Process exited with status 1
2017-12-27T04:07:34.441182+00:00 app[worker.1]: module.js:538
2017-12-27T04:07:34.441203+00:00 app[worker.1]:     throw err;
2017-12-27T04:07:34.441204+00:00 app[worker.1]:     ^
2017-12-27T04:07:34.441205+00:00 app[worker.1]: 
2017-12-27T04:07:34.441206+00:00 app[worker.1]: Error: Cannot find module '/app/build/index.js'
2017-12-27T04:07:34.441207+00:00 app[worker.1]:     at Function.Module._resolveFilename (module.js:536:15)
2017-12-27T04:07:34.441207+00:00 app[worker.1]:     at Function.Module._load (module.js:466:25)
2017-12-27T04:07:34.441208+00:00 app[worker.1]:     at Function.Module.runMain (module.js:676:10)
2017-12-27T04:07:34.441208+00:00 app[worker.1]:     at startup (bootstrap_node.js:187:16)
2017-12-27T04:07:34.441209+00:00 app[worker.1]:     at bootstrap_node.js:608:3
```

**Comment by amachino** [comment]
It worked using `postinstall` in package.json, instead of `release` in Procfile.

commit: https://github.com/tipether/tipether/commit/871ef830466385b178a9d4077320d92351cd06af

https://devcenter.heroku.com/articles/nodejs-support#build-behavior

**Comment by kentaro** [comment]
Looks fine!

**Pull request closed without merging**
